local EliteSQL = {}

function EliteSQL.importEliteScheduleItemData()
   
ImportScheduleItemsFromElite = [[SELECT DISTINCT 
TRIM(PROD_841_D.ITEM.ITEM_NUM) AS ITEM_NUM,
DECODE(PROD_841_D.ITEM_CE.IS_LICENSE_REQ,1,'Y','N') AS LIC_REQD, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'I','Y','N') AS SCHED1, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'II','Y','N') AS SCHED2, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'III','Y','N') AS SCHED3, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'IV','Y','N') AS SCHED4, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'V','Y','N') AS SCHED5, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'VI','Y','N') AS SCHED6, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'VII','Y','N') AS SCHED7, 
DECODE(TRIM(PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST),'VIII','Y','N') AS SCHED8, 
TRIM(PROD_841_D.ITEM_2.BACCS) AS BACCS, 
TRIM(PROD_841_D.ITEM_2.BREAK_CODE)AS BREAK_CODE,
TRIM(PROD_841_D.ITEM_2.USE_BREAK_CODE) AS USE_BREAK_CODE,
TRIM(PROD_841_D.ITEM.UPC)AS UPC,
TRIM(PROD_841_D.ITEM.DESC_1)AS DESC_1
          FROM ((PROD_841_D.ITEM INNER JOIN PROD_841_D.ITEM_CE ON PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM) 
          INNER JOIN PROD_841_D.ITEM_LICENSE_CE 
          ON PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM and prod_841_D.Item_LICENSE_CE.LICENSE_TYPE=2) 
          INNER JOIN PROD_841_D.ITEM_2 
          ON PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_2.ITEM_NUM
          WHERE 
          (
          (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='I' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                OR 
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='II' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='IIN' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='III' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                 OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='IIIN' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                 OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='IV' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                 OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST='V' )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                 OR
                (
                        ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_CE.ITEM_NUM ) AND ( PROD_841_D.ITEM.ITEM_NUM = PROD_841_D.ITEM_LICENSE_CE.ITEM_NUM )  
                        AND ( PROD_841_D.ITEM_LICENSE_CE.DEA_SCHEDULE_LIST IS NULL )   AND ( PROD_841_D.ITEM_2.ITEM_NUM=PROD_841_D.ITEM.ITEM_NUM )
                )
                
                )
                
                AND
            
            ( PROD_841_D.ITEM.DESC_1 NOT LIKE '%DO NOT USE%' AND PROD_841_D.ITEM.DESC_1 NOT LIKE 'DISPOSAL%' )
            
            ]]
end
return EliteSQL